#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A AFVAW00262F03
#PBS -q debug
#PBS -l select=2:ncpus=48:mpiprocs=48
#PBS -l walltime=01:00:00
#PBS -j oe
#
## Optional Directives ------------------------------------
#PBS -M lenard.halim@gatech.edu
#PBS -m be

cd $PBS_O_WORKDIR
source $HOME/.bashrc
source $HOME/.profile
#export CMPLX_MODE=1
time mpiexec_mpt -n 1 python pyopt_adjoint_heat_flux.py 2>&1 > opt.out
